const signals=[
 {league:'Argentina — Liga Profesional',time:'18:30 BRT',home:'Aldosivi',away:'Atlético Tucumán',score:64,tag:'CANDIDATO',reason:'Fontes atuais apontam sinais de gols dos dois lados; usar como teste do motor.'},
 {league:'Argentina — Liga Profesional',time:'23:15 BRT',home:'Barracas Central',away:'Independiente Rivadavia',score:61,tag:'CANDIDATO',reason:'Prévia atual cita BTTS como mercado relevante; score ainda provisório.'},
 {league:'Argentina — Liga Profesional',time:'23:15 BRT',home:'Lanús',away:'Estudiantes',score:24,tag:'EVITAR',reason:'Dados recentes consultados mostram BTTS Yes em apenas 3/10 do Lanús e 2/10 em casa.'},
 {league:'Brasil — Série B',time:'19:30 BRT',home:'Criciúma',away:'Operário Ferroviário',score:55,tag:'OBSERVAR',reason:'Operário vem de 3–3; Criciúma perdeu os dois últimos. Falta completar o histórico estruturado.'},
 {league:'Brasil — Série B',time:'21:30 BRT',home:'Cuiabá',away:'Náutico',score:52,tag:'OBSERVAR',reason:'Jogo disponível na janela da Data FIFA; score fica provisório até o histórico estruturado.'}
];
const state=JSON.parse(localStorage.getItem('btts_pro')||'{"bankroll":1000,"pnl":0,"greens":0,"reds":0,"stakes":[]}');
const br=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function render(){document.querySelector('#bankroll').textContent=br(state.bankroll);document.querySelector('#pnl').textContent=(state.pnl>=0?'+':'')+br(state.pnl);document.querySelector('#n').textContent=signals.filter(x=>x.score>=55).length;document.querySelector('#g').textContent=state.greens;document.querySelector('#r').textContent=state.reds;const ex=state.stakes.reduce((a,b)=>a+b,0);document.querySelector('#roi').textContent=(ex?(state.pnl/ex*100):0).toFixed(1)+'%';document.querySelector('#avg').textContent=Math.round(signals.reduce((a,x)=>a+x.score,0)/signals.length);document.querySelector('#updated').textContent='21/09/2026';document.querySelector('#list').innerHTML=signals.map(x=>`<article class="card"><div class="league">${x.league}</div><div class="match">${x.home} × ${x.away}</div><div class="meta"><span>${x.time}</span><span>Score ${x.score}</span></div><div class="bar"><i style="width:${x.score}%"></i></div><div class="bottom"><span>${x.reason}</span><span class="badge">${x.tag}</span></div></article>`).join('')}
document.querySelector('#refresh').onclick=render; if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
